---
title: "R Notebook"
output: html_notebook
---

Import the necessary libraries
```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(WDI)
library(corrplot)
library(GGally)
library(factoextra)
library(cluster)
library(fpc)
library(ggpubr)
library(MASS)
library(lubridate)
library(ggstatsplot)
```
```{r}
new_wdi_cache<-WDIcache()
```

```{r}
WDI<-WDI(country = "all",
         indicator = c("NY.GDP.MKTP.KD.ZG","NV.IND.MANF.ZS", "NV.SRV.TOTL.ZS", "NV.IND.TOTL.ZS", "NV.AGR.TOTL.ZS"),
         start = 2020,
         end = 2020,
         extra = TRUE,
         cache = new_wdi_cache)
```

```{r}

covidData<-read.csv("covidData.csv")

```

```{r}
covidDF<-data.frame(covidData[,( colnames(covidData) %in% c('iso_code',
                    'continent',
                    'location',
                    'date',
                    'total_cases_per_million',
                    'total_deaths_per_million',
                    'total_vaccinated_per_hundred',
                    'gdp_per_capita',
                    'life_expectancy',
                    'human_development_index',
                    'population_density',
                    'hospital_beds_per_thousand',
                    'total_vaccinations_per_hundred'))])
```

```{r}
covidDF_stringency<-data.frame(covidData[, (colnames(covidData) %in% c('iso_code',
                                                                       'location',
                                                                       'date',
                                                                       "stringency_index"))])

stringency_2020<-covidDF_stringency %>% filter(date <= as.Date("2020-12-31"))
```

```{r}
stringency_mean<-stringency_2020 %>%
  group_by(location) %>%
  summarise(stringency_index = mean(stringency_index, na.rm = TRUE))
colnames(stringency_mean)<-c("location", "mean_stringency_idx")

stringency_max<-stringency_2020 %>%
  group_by(location) %>%
  summarise(stringency_index = max(stringency_index, na.rm = TRUE))
colnames(stringency_max)<-c("location", "max_stringency_idx")
```


```{r}
WDI_DF<-data.frame(WDI$country, WDI$NY.GDP.MKTP.KD.ZG, WDI$NV.SRV.TOTL.ZS, WDI$NV.IND.TOTL.ZS, WDI$NV.AGR.TOTL.ZS)

colnames(WDI_DF)<-c("location", "GDP_growth_rate_2020", "service_sect", "industry_sect", "agriculture_sect")

WDI_DF2<-WDI_DF%>%mutate(total = service_sect+industry_sect+agriculture_sect)
```


```{r}
covidDF<-filter(covidDF, date=="2020-12-31")
covidDF<-merge(covidDF, WDI_DF,by = "location")
covidDF<-merge(covidDF, stringency_mean, by = "location")
covidDF<-merge(covidDF, stringency_max, by = "location")

```

```{r}
covidDF<-mutate_at(covidDF, c("total_vaccinations_per_hundred"), ~replace(., is.na(.),0.0))
```


```{r}

covidDF<-na.omit(covidDF)
```

```{r}
Q<-quantile(covidDF$GDP_growth_rate_2020, probs = c(.25, .75), na.rm = FALSE)
iqr<-IQR(covidDF$GDP_growth_rate_2020)
up<-Q[2]+1.5*iqr
low<-Q[2]-1.5*iqr
```



```{r}
covidDF_no_outlier<-subset(covidDF, covidDF$GDP_growth_rate_2020>low & covidDF$GDP_growth_rate_2020<up)

```


```{r}
cor_data1<-select_if(covidDF_no_outlier, is.numeric)
cor = cor(cor_data1)
corrplot(cor, method = 'number')
```


# ```{r}
# covidDF_selected<-data.frame(covidDF[,( colnames(covidDF) %in% c(
#                     'location',
#                     'total_deaths_per_million',
#                     'human_development_index',
#                     'service_sect',
#                     'industry_sect',
#                     'max_stringency_idx'))])
# ```





```{r}
covidDF_clean<-na.omit(covidDF_no_outlier)
covidDF_sclaed<-scale(covidDF_clean[,c(4:17)])
```


```{r}
fviz_nbclust(
  covidDF_sclaed,
  FUNcluster = kmeans,
  method = "wss",
  diss = NULL,
  k.max = 20,
  nboot = 100,
  verbose = interactive(),
  barfill = "steelblue",
  barcolor = "steelblue",
  linecolor = "steelblue",
  print.summary = TRUE
)
```


```{r}
pamk_result<-pamk(covidDF_sclaed,krange=3,criterion="asw", usepam=TRUE,
     scaling=FALSE, alpha=0.001, diss=inherits(data, "dist"),
     critout=FALSE, ns=10, seed=NULL)
```

```{r}
clusters<-data.frame(pamk_result$pamobject$clustering)
```

```{r}
covidDF_clean<-cbind(covidDF_clean, clusters)
```

```{r}
colnames(covidDF_clean)[18]<-"clusters"
```

```{r}
deaths<-ggplot(covidDF_clean,aes(x=as.character(clusters), y=total_deaths_per_million))+geom_boxplot()
# gdp_growth<-ggplot(covidDF_clean, aes(x=as.character(clusters), y=GDP_growth_rate_2020))+geom_boxplot()
hdi<-ggplot(covidDF_clean,aes(x=as.character(clusters), y=human_development_index))+geom_boxplot()
string<-ggplot(covidDF_clean,aes(x=as.character(clusters), y=stringency_max))+geom_boxplot()
serv<-ggplot(covidDF_clean,aes(x=as.character(clusters), y=service_sect))+geom_boxplot()
inds<-ggplot(covidDF_clean,aes(x=as.character(clusters), y=industry_sect))+geom_boxplot()

```

```{r}
# plot<-ggarrange(deaths, hdi, string, serv, inds, ncol = 2)
# plot
string
```
```{r}
hist_cases<-ggplot(covidDF_clean, aes(total_cases_per_million))+geom_histogram()
hist_death<-ggplot(covidDF_clean, aes(total_deaths_per_million))+geom_histogram()
# hist_dens<-ggplot(covidDF_clean, aes(population_density))+geom_histogram()
hist_gdp<-ggplot(covidDF_clean, aes(gdp_per_capita))+geom_histogram()
hist_gdp_growth<-ggplot(covidDF_clean, aes(GDP_growth_rate_2020))+geom_histogram()
hist_life<-ggplot(covidDF_clean, aes(life_expectancy))+geom_histogram()
hist_hdi<-ggplot(covidDF_clean, aes(human_development_index))+geom_histogram()

hist_plot<-ggarrange(hist_cases, hist_death, hist_gdp, hist_gdp_growth,hist_life, hist_hdi, nrow = 3, ncol = 2)
hist_plot
```

```{r}
ks.test(covidDF_clean$total_cases_per_million, "pnorm")
ks.test(covidDF_clean$total_deaths_per_million, "pnorm")
ks.test(covidDF_clean$gdp_per_capita, "pnorm")
ks.test(covidDF_clean$GDP_growth_rate_2020, "pnorm")
ks.test(covidDF_clean$life_expectancy, "pnorm")
ks.test(covidDF_clean$human_development_index, "pnorm")
```
```{r}
kruskal.test(total_cases_per_million~clusters, data = covidDF_clean)
kruskal.test(total_deaths_per_million~clusters, data = covidDF_clean)
kruskal.test(gdp_per_capita~clusters, data = covidDF_clean)
kruskal.test(GDP_growth_rate_2020~clusters, data = covidDF_clean)
kruskal.test(life_expectancy~clusters, data = covidDF_clean)
kruskal.test(human_development_index~clusters, data = covidDF_clean)
```

```{r}
covidDF_clean_scaled<-data.frame(cbind(covidDF_clean[,1:3], covidDF_sclaed, clusters))
```
```{r}
pca<-prcomp(covidDF_clean_scaled[,4:17])
covidPCA<-data.frame(covidDF_clean_scaled,
                     PC1=pca$x[,1],
                     PC2=pca$x[,2])

```


```{r}
colnames(covidPCA)[18]<-"clusters"
```

```{r}
ggplot(covidPCA,aes(PC1, PC2))+geom_point(aes(col=as.character(clusters)), size = 3)
```

```{r}
WDI_select<-data.frame(WDI$country, WDI$income)
colnames(WDI_select)<-c("location", "income")
complete_data<-merge(covidPCA, WDI_select, by = )
complete_data<-subset(complete_data, location != "World")
```


```{r}
ggplot(complete_data,aes(PC1, PC2))+geom_point(aes(col=as.character(clusters), shape = income), size = 3)

```

```{r}
chisq.test(complete_data$clusters, complete_data$income)
```
```{r}
kruskal.test(clusters~GDP_growth_rate_2020, data = complete_data)
```


# ```{r}
# ggplot(complete_data, aes(clusters, income, label = location))+geom_jitter()+geom_text(size = 2)
# ```
# ```{r}
# cor_data<-select_if(complete_data, is.numeric)
# cor = cor(cor_data)
# corrplot(cor, method = 'number')
# ```


```{r}
cluster1<-filter(complete_data, clusters == 1)
cluster2<-filter(complete_data, clusters == 2)
cluster3<-filter(complete_data, clusters == 3)
```

```{r}

cor_data_m1<-select_if(cluster1, is.numeric)
cor = cor(cor_data_m1)
corrplot(cor, method = 'number')
```


```{r}
model1<-lm(formula = GDP_growth_rate_2020~total_deaths_per_million+gdp_per_capita+service_sect+industry_sect+agriculture_sect, data = cluster1)

summary(model1)
```

```{r}
plot(model1, which = 1)
```
```{r}
ggplot(cluster1, aes(GDP_growth_rate_2020))+geom_boxplot()
```
```{r}
cor_data_m1<-select_if(cluster1, is.numeric)
cor = cor(cor_data_m1)
corrplot(cor, method = 'number')
```


```{r}
gdp_prediction1<-data.frame(location = cluster1$location, actual = cluster1$GDP_growth_rate_2020, pred = model1$fitted.values)



satu<-ggplot(data = gdp_prediction1, aes(actual, pred))+geom_point()+geom_abline(mapping=aes(slope=1, intercept = 0), color='red')+geom_text(aes(label = location))
```

```{r}
layout(matrix(c(1,2,3,4),2,2))
plot(model1)
```

```{r}
cor_data_m3<-select_if(cluster3, is.numeric)
cor = cor(cor_data_m3)
corrplot(cor, method = 'number')
```

```{r}
model3<-lm(formula = GDP_growth_rate_2020~total_deaths_per_million+population_density+gdp_per_capita+service_sect+industry_sect+max_stringency_idx+mean_stringency_idx, data = cluster3)

summary(model3)
```

```{r}
gdp_prediction3<-data.frame(location = cluster3$location, actual = cluster3$GDP_growth_rate_2020, pred = model3$fitted.values)



tiga<-ggplot(data = gdp_prediction3, aes(actual, pred))+geom_point()+geom_abline(mapping=aes(slope=1, intercept = 0), color='red')+geom_text(aes(label = location))
```



```{r}
cor_data_m2<-select_if(cluster2, is.numeric)
cor = cor(cor_data_m2)
corrplot(cor, method = 'number')
```

```{r}
model2<-lm(formula = GDP_growth_rate_2020~total_deaths_per_million+total_vaccinations_per_hundred+population_density+hospital_beds_per_thousand+service_sect+industry_sect+max_stringency_idx+mean_stringency_idx, data = cluster2)

summary(model2)
```

```{r}
gdp_prediction2<-data.frame(location = cluster2$location, actual = cluster2$GDP_growth_rate_2020, pred = model2$fitted.values)



dua<-ggplot(data = gdp_prediction2, aes(actual, pred))+geom_point()+geom_abline(mapping=aes(slope=1, intercept = 0), color='red')+geom_text(aes(label = location))
```





```{r}

cor_data_all<-select_if(complete_data, is.numeric)
cor = cor(cor_data_all)
corrplot(cor, method = 'number')
```

```{r}
model4<-lm(formula = GDP_growth_rate_2020~total_deaths_per_million+human_development_index+service_sect+industry_sect+max_stringency_idx, data = complete_data)

summary(model4)
```

```{r}
gdp_prediction4<-data.frame(location = complete_data$location, actual = complete_data$GDP_growth_rate_2020, pred = model4$fitted.values)



empat<-ggplot(data = gdp_prediction4, aes(actual, pred))+geom_point()+geom_abline(mapping=aes(slope=1, intercept = 0), color='red')+geom_text(aes(label = location))
```

```{r}
plot<-ggarrange(satu, dua, tiga, empat, ncol = 2)
plot
```

```{r}
moodelc1<-lm(formula = GDP_growth_rate_2020~total_deaths_per_million+human_development_index+service_sect+industry_sect+max_stringency_idx, data = cluster1)

moodelc2<-lm(formula = GDP_growth_rate_2020~total_deaths_per_million+human_development_index+service_sect+industry_sect+max_stringency_idx, data = cluster2)

moodelc3<-lm(formula = GDP_growth_rate_2020~total_deaths_per_million+human_development_index+service_sect+industry_sect+max_stringency_idx, data = cluster3)

moodelc4<-lm(formula = GDP_growth_rate_2020~total_deaths_per_million+human_development_index+service_sect+industry_sect+max_stringency_idx, data = complete_data)
```

```{r}
summary(moodelc1)
summary(moodelc2)
summary(moodelc3)
summary(moodelc4)
```

```{r}


cluster1_ori<-filter(covidDF_clean, clusters == 1)
cluster2_ori<-filter(covidDF_clean, clusters == 2)
cluster3_ori<-filter(covidDF_clean, clusters == 3)


modelORI1<-lm(formula = GDP_growth_rate_2020~total_deaths_per_million+gdp_per_capita+service_sect+industry_sect+agriculture_sect, data = cluster1_ori)

modelORI2<-lm(formula = GDP_growth_rate_2020~total_cases_per_million+total_deaths_per_million+total_vaccinations_per_hundred+population_density+hospital_beds_per_thousand+service_sect+industry_sect+agriculture_sect, data = cluster2_ori)

modelORI3<-lm(formula = GDP_growth_rate_2020~total_deaths_per_million+population_density+gdp_per_capita+service_sect+industry_sect, data = cluster3_ori)

modelORI4<-lm(formula = GDP_growth_rate_2020~total_deaths_per_million+human_development_index+service_sect+max_stringency_idx, data = covidDF_clean)


summary(modelORI1)
summary(modelORI2)
summary(modelORI3)
summary(modelORI4)
```

```{r}

gdp_prediction1_ori<-data.frame(location = cluster1_ori$location, actual = cluster1_ori$GDP_growth_rate_2020, pred = modelORI1$fitted.values)

gdp_prediction2_ori<-data.frame(location = cluster2_ori$location, actual = cluster2_ori$GDP_growth_rate_2020, pred = modelORI2$fitted.values)

gdp_prediction3_ori<-data.frame(location = cluster3_ori$location, actual = cluster3_ori$GDP_growth_rate_2020, pred = modelORI3$fitted.values)

gdp_prediction4_ori<-data.frame(location = covidDF_clean$location, actual = covidDF_clean$GDP_growth_rate_2020, pred = modelORI4$fitted.values)



satu_ori<-ggplot(data = gdp_prediction1_ori, aes(actual, pred))+geom_point()+geom_abline(mapping=aes(slope=1, intercept = 0), color='red')+geom_text(aes(label = location))

dua_ori<-ggplot(data = gdp_prediction2_ori, aes(actual, pred))+geom_point()+geom_abline(mapping=aes(slope=1, intercept = 0), color='red')+geom_text(aes(label = location))

tiga_ori<-ggplot(data = gdp_prediction3_ori, aes(actual, pred))+geom_point()+geom_abline(mapping=aes(slope=1, intercept = 0), color='red')+geom_text(aes(label = location))

empat_ori<-ggplot(data = gdp_prediction4_ori, aes(actual, pred))+geom_point()+geom_abline(mapping=aes(slope=1, intercept = 0), color='red')+geom_text(aes(label = location))

plot<-ggarrange(satu_ori, dua_ori, tiga_ori, empat_ori, ncol = 2)
plot
```
```{r}
ggplot(complete_data,aes(GDP_growth_rate_2020,service_sect))+geom_point(aes(col=as.character(clusters), shape = income), size = 3)
```

